name: Cypress Tests

on:
  # push:
  #   branches: [ main, master ]
  # pull_request:
  #   branches: [ main, master ]
  workflow_dispatch:

jobs:
  cypress-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browsers: [chrome, firefox]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Clean Reports
      run: npm run clean:reports

    - name: Cypress Tests
      uses: cypress-io/github-action@v6
      with:
        browser: ${{ matrix.browsers }}
        headed: false
        spec: cypress/e2e/*.cy.js
        install: false # since we already ran npm ci
        
    - name: Generate Report
      if: always()
      run: npm run report:generate

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-report-${{ matrix.browsers }}
        path: |
          cypress/reports
          cypress/screenshots
          cypress/videos
        retention-days: 30